### ISSUE TITLE
Plugin causes auto-import suggestions to no longer display

### ISSUE THREAD

**Issue by lemcii** [tw-in-js/vscode-twind-intellisense#2]
When I enable this plugin, TypeScript auto-import intellisense seems to stop working.

**Comment by sastan** [comment]
Yep. I noticed that too. Not sure why. I'm investigating.

**Comment by Andrewnt219** [comment]
Hi @sastan ,

Are there any updates on this issue, or maybe a workaround?

**Comment by sastan** [comment]
No. Sorry... I hope to find some time at the end of the week.

**Comment by ratorx** [comment]
I have the same problem. I think this is likely an issue in the typescript plugin (rather than anything here), because I have the exact same issue with that as well. I'll open an issue in the repo for the typescript plugin.

**Comment by mattrossman** [comment]
Just got bitten by this bug, was poring over VSCode issue threads trying to figure out why my auto imports haven't been working.

**Comment by IgnusG** [comment]
Another library seems to have had a similar issue. Might be related https://github.com/runem/lit-analyzer/issues/200
