### ISSUE TITLE
doesn't work in deno environment

### ISSUE THREAD

**Issue by asrvd** [tw-in-js/vscode-twind-intellisense#9]
I'm using twind with [fresh.deno.dev](https://fresh.deno.dev) but the extension doesn't work in any file.

**Comment by heliumbrain** [comment]
Not sure what the best solution is, but it seems like the plugin is not activating since it can't find a twind config file. Creating a `./config/twind.config.ts` file with the following content will make it work:

```
/** @jsx h */

/** @type {import('twind').Configuration} */
```

**Comment by asrvd** [comment]
works, thanks!

![image](https://user-images.githubusercontent.com/68690233/177051330-4cdf8cfa-b92c-4ac2-9ad8-9bccd3354877.png)

**Comment by ps6067966** [comment]
> /** @jsx h */
> 
> /** @type {import('twind').Configuration} */

Thank you, it's working.

**Comment by WishYouANiceDay** [comment]
> Not sure what the best solution is, but it seems like the plugin is not activating since it can't find a twind config file. Creating a `./config/twind.config.ts` file with the following content will make it work:
> 
> ```
> /** @jsx h */
> 
> /** @type {import('twind').Configuration} */
> ```

Awesome! Thanks:)
